# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  PROJECT_PATH: DemoAutomation.uproject
  ENGINE_PATH: 'C:\Epic\UE_5.4'

jobs:
  hackcheck:
    name: Unreal Engine C++ Lint
    runs-on: self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run UAT Check
        shell: cmd
        run: |
          dir %GITHUB_WORKSPACE%
          echo %cd%
          RunLintTest.bat
  
  EditorTesting:
    name: Testing editor automation unreal
    runs-on: self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run UAT Check
        shell: cmd
        run: |
          dir %GITHUB_WORKSPACE%
          echo %cd%
          RunTestsEditor.bat

  build:
    name: Build & Run Packaged Tests
    runs-on: self-hosted
    needs: EditorTesting
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build and Package
        run: |
          cmd mkdir Build
          & "${{ env.ENGINE_PATH }}\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun `
            -project="%GITHUB_WORKSPACE%\GG.uproject" `
            -noP4 -platform=Win64 -clientconfig=Shipping -serverconfig=Development `
            -cook -allmaps -build -stage -pak -archive `
            -archivedirectory="%GITHUB_WORKSPACE%\Build"
